### ISSUE TITLE
The retargeting tool

### ISSUE THREAD

**Issue by yzhang-gh** [kbrodt/sketch2pose#3]
Hi, thanks for sharing this interesting work.

Just curious about what is the retargeting tool you used in the paper. It says "Blender's Animation Retargeting feature" but AFAIK there isn't an official tool for it. Did you use other add-ons?

**Comment by kbrodt** [comment]
Hi, I used https://github.com/Mwni/blender-animation-retargeting

**Comment by yzhang-gh** [comment]
Thank you!
